on: [push, pr]

name: build

jobs:
  haskell:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.8.3'
          enable-stack: true
          stack-version: 'latest'
      - run: stack build
      - run: stack test
